### ISSUE TITLE
Trying to make it work. Doesn't on Fly.io

### ISSUE THREAD

**Issue by rodrialbanese** [hrumhurum/docker-recipes#1] opened 2023-01-26 01:48 UTC
Im following your steps, but it seems it doesn't work on fly.
The console says cron is running and crontab has the work loaded as in:

```
# service cron status
cron is running.
```

```
# crontab -l
SHELL=/bin/sh
* * * * * /app/every_1min.sh >> /app/var/log/cron.log 2>&1
```

The log file is never created. But if i manually run /app/every_1min.sh >> /app/var/log/cron.log 2>&1, it is. And every time I run it it appends a new line as expected.

**Comment by hrumhurum** [comment] 2023-01-26 17:23
I've tried to reproduce the issue, and this is what I've got: https://green-lake-3115.fly.dev/

The log file is correctly created and updated by cron: https://green-lake-3115.fly.dev/logs/cron.log

Any ideas why it may not work for you? What fly's app log is saying?

**Comment by hrumhurum** [comment] 2023-02-07 22:20
I'm closing the issue because it is related to external code base and does apply to the projects in this repository.

**Closed as completed by hrumhurum** 2023-02-07 22:20 UTC
